name: Unit Tests

on:
  pull_request:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest requests numpy joblib scikit-learn
     
      - name: Fix NumPy Import Issue
        run: |
          pip uninstall -y numpy
          pip install --no-cache-dir numpy


      - name: Run unit tests
        run: |
          python -m pytest tests/